jobs:
  - script: |
      pipelineJob('HelloWorld/Backend') {
          description('Backend Hello World Pipeline')
          properties {
              disableConcurrentBuilds()
          }
          definition {
              cpsScm {
                  scm {
                      git {
                          remote {
                              url 'https://github.com/mamrezb/jenkinsmaster-backend-helloworld.git'
                          }
                          branches 'main'
                          extensions {}
                      }
                  }
                  scriptPath 'Jenkinsfile'
              }
          }
      }
